version: '3.3'

volumes:
  postgres_data:
  static_files:
  media_files:

healthcheck:
  test: curl -s http://web:80 || echo 1
  interval: 5m
  timeout: 30s
  retries: 4

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: fedormityanin/foodgram-project:latest
    restart: always
    volumes:
      - static_files:/code/static
      - media_files:/code/media
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_files:/var/www/static
      - media_files:/var/www/media
    ports:
      - "80:80"
    depends_on:
      - web
