# Generated by Django 3.2.4 on 2021-06-17 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210610_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Сколько класть?', validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиентов не может быть ноль или меньше')], verbose_name='Количество'),
        ),
    ]
