# Generated by Django 3.1.7 on 2021-03-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=10, verbose_name='Цвет тэга'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True, verbose_name='Слаг тэга'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=10, unique=True, verbose_name='Имя тэга'),
        ),
    ]
