# Generated by Django 3.1.7 on 2021-03-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210317_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags_in_recipe',
            field=models.ManyToManyField(blank=True, through='recipes.TagsInRecipe', to='recipes.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tagsinrecipe',
            unique_together={('recipe', 'tag')},
        ),
    ]
