# Generated by Django 3.1.7 on 2021-04-05 04:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0013_auto_20210404_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'recipe')},
        ),
    ]
