# Generated by Django 3.1.7 on 2021-04-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20210411_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_in_recipe',
            field=models.ManyToManyField(through='recipes.IngredientsInRecipe', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_to_cook',
            field=models.PositiveSmallIntegerField(help_text='Введите время готовки в минутах', verbose_name='Время приготовления'),
        ),
    ]
