# Generated by Django 3.1.7 on 2021-05-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210506_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsinrecipe',
            options={'verbose_name': 'Ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='tagsinrecipe',
            options={'verbose_name': 'Тэг рецепта', 'verbose_name_plural': 'Тэги рецепта'},
        ),
    ]
