# Generated by Django 3.1.7 on 2021-05-06 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20210506_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Сколько класть?', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_to_cook',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
    ]
