# Generated by Django 3.1.7 on 2021-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20210508_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags_in_recipe',
            field=models.ManyToManyField(through='recipes.TagsInRecipe', to='recipes.Tag', verbose_name='Тэги'),
        ),
    ]
