# Generated by Django 3.1.7 on 2021-05-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_auto_20210510_1734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientsinrecipe',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
